import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

// Environment variables
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')!
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!
const FRONTEND_URL = Deno.env.get('FRONTEND_URL') || 'https://pilotodedrones.cl'

const corsHeaders = {
	'Access-Control-Allow-Origin': '*',
	'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

function generatePassword(length = 8) {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
	let retVal = "";
	for (let i = 0, n = charset.length; i < length; ++i) {
		retVal += charset.charAt(Math.floor(Math.random() * n));
	}
	return retVal;
}

const PERMISSION_LABELS: Record<string, string> = {
	create_diplomas: 'Crear Diplomas',
	manage_certificates: 'Gestionar Certificados',
	approve_deny_certificates: 'Aprobar/Denegar Certificados',
	view_users: 'Ver Usuarios',
	view_companies: 'Ver Empresas',
	view_notifications: 'Ver Notificaciones',
	manage_banners: 'Gestionar Banners',
	upload_banners: 'Subir Banners de Publicidad',
};

serve(async (req) => {
	if (req.method === 'OPTIONS') {
		return new Response('ok', { headers: corsHeaders })
	}

	try {
		// 1. Security Check
		const authHeader = req.headers.get('Authorization')
		if (!authHeader) {
			return new Response(JSON.stringify({ error: 'No autorizado' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
		}

		const supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { global: { headers: { Authorization: authHeader } } })
		const { data: { user: currentUser }, error: authError } = await supabaseClient.auth.getUser()

		if (authError || !currentUser) {
			return new Response(JSON.stringify({ error: 'Token inválido o expirado' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
		}

		const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

		// Verify Caller Role (Must be Admin or Super Admin)
		const { data: roleData } = await supabaseAdmin
			.from('user_roles')
			.select('role')
			.eq('id', currentUser.id)
			.single()

		const isAllowed = roleData?.role === 'super_admin' || roleData?.role === 'admin';
		if (!isAllowed) {
			return new Response(JSON.stringify({ error: 'Permisos insuficientes.' }), { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
		}

		// 2. Process Request
		const { email, full_name, permissions } = await req.json()

		if (!email || !permissions) {
			return new Response(JSON.stringify({ error: 'Faltan datos requeridos (email, permissions)' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
		}

		const cleanEmail = email.toLowerCase().trim()
		const invitedBy = currentUser.id

		// 3. Find user by email in Auth
		const { data: { users: foundUsers }, error: findError } = await supabaseAdmin.auth.admin.listUsers({
			filter: { email: cleanEmail }
		})

		let targetUserId = foundUsers?.[0]?.id;
		let autoGeneratedPassword = '';
		let isNewUser = false;

		if (!targetUserId) {
			// --- CREATE NEW USER ---
			isNewUser = true;
			autoGeneratedPassword = generatePassword(8);

			const { data: newUser, error: createError } = await supabaseAdmin.auth.admin.createUser({
				email: cleanEmail,
				password: autoGeneratedPassword,
				email_confirm: true, // Auto confirm so they can login immediately
				user_metadata: { full_name: full_name || '' }
			});

			if (createError) {
				console.error('Error creating user:', createError);
				throw createError;
			}

			targetUserId = newUser.user.id;

			// Create profile for new user
			await supabaseAdmin.from('profiles').upsert({
				id: targetUserId,
				email: cleanEmail,
				full_name: full_name || '',
				user_type: 'pilot' // Default type
			});

			console.log('New user created with password:', autoGeneratedPassword);
		}

		// --- ASSIGN ROLE AND PERMISSIONS ---

		// Update Role to Admin (if not already Super Admin)
		const { data: existingRole } = await supabaseAdmin
			.from('user_roles')
			.select('role')
			.eq('id', targetUserId)
			.maybeSingle();

		if (existingRole?.role !== 'super_admin') {
			await supabaseAdmin.from('user_roles').upsert({
				id: targetUserId,
				role: 'admin'
			});
		}

		// Update Permissions
		await supabaseAdmin.from('user_permissions').delete().eq('user_id', targetUserId);

		if (permissions && permissions.length > 0) {
			const permsToInsert = permissions.map((p: string) => ({
				user_id: targetUserId,
				permission: p,
				granted_by: invitedBy
			}));
			await supabaseAdmin.from('user_permissions').insert(permsToInsert);
		}

		// --- PREPARE EMAILS ---
		let emailSubject = '';
		let emailHtml = '';
		const mappedPermissions = permissions.map((p: string) => PERMISSION_LABELS[p] || p);

		if (isNewUser) {
			emailSubject = '¡Bienvenido! Tu cuenta de Administrador ha sido creada';
			emailHtml = `
      <!DOCTYPE html>
      <html>
      <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="background-color: #083b4e; padding: 25px; text-align: center;">
          <h1 style="color: white; margin: 0;">Piloto de Drones</h1>
        </div>
        <div style="padding: 30px; border: 1px solid #edf2f7; border-top: 0; border-radius: 0 0 8px 8px;">
          <h2 style="color: #2d3748;">${full_name ? `Hola ${full_name},` : '¡Hola!'}</h2>
          <p>Has sido invitado a formar parte del equipo de <strong>Administradores</strong> en Piloto de Drones.</p>
          
          <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin: 25px 0; border: 1px solid #e2e8f0;">
            <p style="margin: 0 0 10px; color: #4a5568;">Tu cuenta ya ha sido creada. <strong>No necesitas registrarte</strong>, solo ingresa con estos datos:</p>
            <p style="margin: 5px 0;"><strong>Email:</strong> ${cleanEmail}</p>
            <p style="margin: 5px 0;"><strong>Contraseña Temporal:</strong> <span style="background: #edf2f7; padding: 2px 6px; border-radius: 4px; font-family: monospace; font-size: 1.1em;">${autoGeneratedPassword}</span></p>
          </div>

          <p>Importante: Ve directamente a la pestaña de <strong>"Iniciar Sesión"</strong>. No intentes crear una cuenta de nuevo ya que tu email ya está registrado.</p>
          
          <div style="margin: 30px 0; text-align: center;">
            <a href="${FRONTEND_URL}/auth" style="background-color: #00b3f3; color: white; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block; box-shadow: 0 4px 6px rgba(0,179,243,0.2);">Ir a Iniciar Sesión</a>
          </div>

          <div style="border-top: 1px solid #edf2f7; pt: 20px; margin-top: 30px;">
            <p style="font-size: 0.9em; color: #718096; margin-bottom: 10px;">Accesos habilitados en tu cuenta:</p>
            <ul style="color: #4a5568; font-size: 0.9em; margin: 0; padding-left: 20px;">
              ${mappedPermissions.map((label: string) => `<li>${label}</li>`).join('')}
            </ul>
          </div>
        </div>
      </body>
      </html>
      `;
		} else {
			emailSubject = 'Tus permisos de Administrador han sido actualizados';
			emailHtml = `
      <!DOCTYPE html>
      <html>
      <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="background-color: #083b4e; padding: 25px; text-align: center;">
          <h1 style="color: white; margin: 0;">Piloto de Drones</h1>
        </div>
        <div style="padding: 30px; border: 1px solid #edf2f7; border-top: 0; border-radius: 0 0 8px 8px;">
          <h2 style="color: #2d3748;">Hola,</h2>
          <p>Te informamos que tus privilegios de <strong>Administrador</strong> en Piloto de Drones han sido otorgados o actualizados.</p>
          
          <div style="background: #e6f7ff; padding: 20px; border-radius: 12px; margin: 25px 0; border-left: 4px solid #00b3f3;">
            <p style="margin: 0 0 10px; font-weight: bold;">Tus permisos actuales:</p>
            <ul style="margin: 0; padding-left: 20px;">
              ${mappedPermissions.map((label: string) => `<li>${label}</li>`).join('')}
            </ul>
          </div>

          <p>Puedes acceder a estas herramientas iniciando sesión normalmente en la plataforma profesional.</p>
          
          <div style="margin: 30px 0; text-align: center;">
            <a href="${FRONTEND_URL}/dashboard" style="background-color: #00b3f3; color: white; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block; box-shadow: 0 4px 6px rgba(0,179,243,0.2);">Ir al Panel de Control</a>
          </div>
        </div>
      </body>
      </html>
      `;
		}

		// --- SEND EMAIL ---
		if (RESEND_API_KEY) {
			const emailRes = await fetch('https://api.resend.com/emails', {
				method: 'POST',
				headers: {
					'Authorization': `Bearer ${RESEND_API_KEY}`,
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					from: 'Piloto de Drones <info@pilotodedrones.cl>',
					to: cleanEmail,
					subject: emailSubject,
					html: emailHtml
				})
			});

			if (!emailRes.ok) {
				const errorText = await emailRes.text();
				console.error('Error sending email via Resend:', errorText);
			} else {
				console.log('Email sent successfully to:', cleanEmail);
			}
		} else {
			console.warn('RESEND_API_KEY not found. Skipping email.');
		}

		const message = isNewUser
			? `Usuario creado con éxito y credenciales enviadas a ${cleanEmail}`
			: `Accesos actualizados y notificación enviada a ${cleanEmail}`;

		return new Response(
			JSON.stringify({ success: true, message }),
			{ status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
		)

	} catch (error: any) {
		console.error('Function error:', error)
		return new Response(
			JSON.stringify({ error: error.message || 'Error interno del servidor' }),
			{ status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
		)
	}
})

