// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sncjozwmtjaltoituumx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuY2pvendtdGphbHRvaXR1dW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjE5NDIsImV4cCI6MjA3NDI5Nzk0Mn0.VfQ7nSK9MPdWBdWweUyOgvWAfQwRsHzkHcXp41M_2vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});